image: ruby:3.4.4

stages:
  - test
  - build
  - attest
  - sign
  - release
  - verify

variables:
  GEM_NAME: "demodemo.gem"
  GEM_SPEC: "demodemo.gemspec"

.install-cosign:
  before_script:
    - wget -O cosign https://github.com/sigstore/cosign/releases/download/v2.5.0/cosign-linux-amd64
    - chmod +x cosign && mv cosign /usr/local/bin/

before_script:
  - bundle install

test:
  script:
    - bundle exec rake

build:
  variables:
    RUNNER_GENERATE_ARTIFACTS_METADATA: true
  script:
    - gem build -o $GEM_NAME $GEM_SPEC
  artifacts:
    name: "$GEM_NAME"    
    paths:
      - $GEM_NAME
