image: ruby:3.4.4

stages:
  - test
  - build
  - attest
  - sign
  - release
  - verify

variables:
  GEM_NAME: "demodemo.gem"
  GEM_SPEC: "demodemo.gemspec"

.install-cosign:
  before_script:
    - wget -O cosign https://github.com/sigstore/cosign/releases/download/v2.5.0/cosign-linux-amd64
    - chmod +x cosign && mv cosign /usr/local/bin/

before_script:
  - bundle install

test:
  script:
    - bundle exec rake

build:
  variables:
    RUNNER_GENERATE_ARTIFACTS_METADATA: true
  script:
    - gem build -o $GEM_NAME $GEM_SPEC
  artifacts:
    name: "$GEM_NAME"    
    paths:
      - $GEM_NAME

attest:
  extends: .install-cosign
  stage: attest
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
    - cosign attest-blob --yes --predicate $GEM_NAME-metadata.json --output-attestation $GEM_NAME.att --output-certificate $GEM_NAME.att.crt --output-signature $GEM_NAME.att.sig --oidc-issuer $CI_SERVER_URL --identity-token $SIGSTORE_ID_TOKEN $GEM_NAME 
  artifacts:
    paths:
      - $GEM_NAME.att
      - $GEM_NAME.att.crt
      - $GEM_NAME.att.sig

sign:
  extends: .install-cosign
  stage: sign
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
    - cosign sign-blob --yes --output-certificate $GEM_NAME.crt --output-signature $GEM_NAME.sig --oidc-issuer $CI_SERVER_URL --identity-token $SIGSTORE_ID_TOKEN $GEM_NAME
  artifacts:
    paths:
      - $GEM_NAME.crt
      - $GEM_NAME.sig

bundle:
  extends: .install-cosign
  stage: release
  script:
    - cosign bundle create --artifact $GEM_NAME --attestation $GEM_NAME.att --certificate $GEM_NAME.crt --signature $GEM_NAME.sig > $GEM_NAME.sigstore.json
  artifacts:
    paths:
      - $GEM_NAME.sigstore.json
      - $GEM_NAME

rubygems:
  stage: release
  dependencies:
    - bundle
  script:
    - ls -lah
    - mkdir -p $HOME/.gem
    - touch $HOME/.gem/credentials
    - chmod 0600 $HOME/.gem/credentials
    - 'echo ":rubygems_api_key: ${GEM_HOST_API_KEY}" >> ~/.gem/credentials'
    - gem push $GEM_NAME --attestation $GEM_NAME.sigstore.json
  artifacts:
    when: always